apiVersion: v1
kind: Service
metadata:
  namespace: kanban-life
  name: pgadmin
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
    tier: frontend
  ports:
  - port: 80
    targetPort: 5050

---

apiVersion: v1
kind: Service
metadata:
  namespace: kanban-life
  name: kanban-web
spec:
  type: LoadBalancer
  selector:
    app: kanban-web
    tier: frontend
  ports:
  - port: 4001
    targetPort: 4001
---

apiVersion: v1
kind: Service
metadata:
  namespace: kanban-life
  name: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
    tier: frontend
  ports:
  - port: 8080
    targetPort: 8080