apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanban-jenkins-pv
  labels:
    type: local
spec:
  storageClassName: manual
  hostPath:
    path: /tmp/jenkins-vol
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: kanban-jenkins-pvc
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
