apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kanban-life
  name: jenkins
spec:
  selector: 
    matchLabels:
      app: jenkins
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
        tier: frontend
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: jenkinsci
          resources:
            requests:
              memory: 500M
              cpu: 500m
            limits:
              memory: 1G
              cpu: 750m
          image: 764625898828.dkr.ecr.us-west-2.amazonaws.com/kanban-ecr:kanban-jenkins
          imagePullPolicy: Always
          # image: jenkins
          # imagePullPolicy: Never
          ports:
          - name: jenkins
            containerPort: 8080
          volumeMounts:
          - name: jenkins-pvc
            mountPath: "/var/jenkins_home"
      volumes:
        - name: jenkins-pvc
          persistentVolumeClaim:
            claimName: kanban-jenkins-pvc
        
        
        
  

  