apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
      tier: frontend
  template:
    metadata:
      labels:
        app: pgadmin
        tier: frontend
    spec:
      containers:
      - name: kanban-db-admin
        image: 764625898828.dkr.ecr.us-west-2.amazonaws.com/kanban-ecr:kanban-pgadmin
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "pgadmin"
          - name: PGADMIN_DEFAULT_PASSWORD
            value: "pgadmin"
          - name: PGADMIN_LISTEN_PORT
            value: "80"
