apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: NodePort
  selector:
    app: pgadmin
    tier: frontend
  ports:
  - port: 80
    targetPort: 5050
    nodePort: 30001

---

apiVersion: v1
kind: Service
metadata:
  name: kanban-web
spec:
  type: NodePort
  selector:
    app: kanban-web
    tier: frontend
  ports:
  - port: 4001
    targetPort: 4001
    nodePort: 30002

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
    tier: frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30003