- name: Deploy the Kanban Life Application
  hosts: localhost
  connection: local

  tasks:
    - name: deploy kanban namespace
      k8s:
        kubeconfig: '/var/jenkins_home/.kube/kubeconfig'
        apply: yes
        definition: "{{ item }}"
        api_key: "{{ lookup('env','jenkins-eks-svc') }}"
      with_items: 
        - "{{ lookup('file', '../../k8s/00_namespace.yaml') }}"
        - "{{ lookup('file', '../../k8s/01_deploy_cloud_services.yaml') }}"
        - "{{ lookup('file', '../../k8s/02_deploy_backend.yaml') }}" 
        - "{{ lookup('file', '../../k8s/03_deploy_frontend.yaml') }}"
        - "{{ lookup('file', '../../k8s/04_deploy_web.yaml') }}"